### ISSUE TITLE
pull access denied for hyper63/hubble-micro

### ISSUE THREAD

**Issue by bliotti** [hyper63/hubble#5]
Not able to access the image from docker, mentioned in [hubble-micro](https://github.com/hyper63/hubble/blob/main/design.md#usage) 

`$ docker run -it -p 8443:8443 -p 9090:9090 -v hubble:/var/hubble --name hubble hyper63/hubble-micro:lts`

returns

```
Unable to find image 'hyper63/hubble-micro:lts' locally
docker: Error response from daemon: pull access denied for hyper63/hubble-micro, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by twilson63** [comment]
Hey @bliotti, 

Yes, this is currently a design document of a potential implementation, I hope we will have an test implementation soon.

Thx

Tom

**Comment by twilson63** [comment]
Hey @bliotti ,

Good news, I have the first build working from docker hub

https://hub.docker.com/repository/docker/hyper63/atlas

You should be able to do the following:

```
docker run -d -v data:/data -p 6363:6363 --name atlas hyper63/atlas
```

Then connect to the cache api

```
curl http://localhost:6363/micro/cache
```

check out this doc for more about the api 

https://gist.github.com/twilson63/91b26ea674914a1e4b73c8c8ec4b20c5
